version: '3.9'

services:
  setup-reverse-proxy:
    env_file:
      - .env
    build:
      context: reverse-proxy
      args:
        - NGINX_CONFIG_TEMPLATE=nginx.conf.setup.template
    volumes:
      - ./data/certbot/www/:${NGINX_WEBROOT}:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - certificate-creation

  certbot:
    container_name: primal-kitchen-certbot
    image: certbot/certbot
    env_file: .env
    volumes:
      - ./data/certbot/www/:${NGINX_WEBROOT}:rw
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
      - ./data/log/letsencrypt/:/var/log/letsencrypt/
    profiles:
      - certificate-creation
      - certificate-setup
    depends_on:
      - setup-reverse-proxy
#    command: certonly --webroot --webroot-path ${NGINX_WEBROOT} --email ${DEVELOPER_EMAIL} --agree-tos --no-eff-email --staging --force-renewal --expand -d ${APP_DOMAIN} -d ${MEDUSA_STOREFRONT_SUBDOMAIN}.${APP_DOMAIN} -d ${MEDUSA_ADMIN_PANEL_SUBDOMAIN}.${APP_DOMAIN} -d ${STRAPI_SUBDOMAIN}.${APP_DOMAIN} -d ${MINIO_SUBDOMAIN}.${APP_DOMAIN}
    command: certonly --webroot --webroot-path ${NGINX_WEBROOT} --email ${DEVELOPER_EMAIL} --agree-tos --no-eff-email --staging --force-renewal --expand -d ${APP_DOMAIN} -d ${MEDUSA_ADMIN_PANEL_SUBDOMAIN}.${APP_DOMAIN} -d ${STRAPI_SUBDOMAIN}.${APP_DOMAIN}
