version: '3.9'

services:
  frontend:
#    build:
#      context: frontend
#      dockerfile: development.dockerfile
    volumes:
      # TODO: where is serve??
      # TODO: gotta be a better way to do this... done to avoid crap getting put on local disk
      - ./frontend/pages:/srv/app/pages
      - ./frontend/components:/srv/app/components
      - ./frontend/public:/srv/app/public
      - ./frontend/styles:/srv/app/styles
      - ./frontend/next.config.js:/srv/app/next.config.js
      - ./frontend/next-env.d.ts:/srv/app/next-env.d.ts
      - ./frontend/tsconfig.json:/srv/app/tsconfig.json
      - ./frontend/.eslintrc.json:/srv/app/eslintrc.json
    command: [ 'npm', 'run', 'dev' ]
