version: '3.9'

services:
  setup-reverse-proxy:
    env_file:
      - .env
    build:
      context: reverse-proxy
      args:
        - NGINX_CONFIG_TEMPLATE=nginx.conf.setup.template
    volumes:
      - ./data/certbot/www/:${NGINX_WEBROOT}:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - certificate-creation

  certbot:
    container_name: primal-kitchen-certbot
    image: certbot/certbot
    env_file: .env
    volumes:
      - ./data/certbot/www/:${NGINX_WEBROOT}:rw
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
      - ./data/log/letsencrypt/:/var/log/letsencrypt/
      - ./scripts/certbot-create-certificate.sh .
    profiles:
      - certificate-creation
      - certificate-setup
    depends_on:
      - setup-reverse-proxy
    entrypoint:
      - ./certbot-create-certificate.sh
