version: '3.9'

# TODO: consider using pebble local acme server instead of m

# just some overwrites to be applied ontop of base docker-compose for hot reloading and volumes. just for better dev experience
services:
  postgres:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  # TODO: i think there may be an issue when requesting strapi data using this development config... need to check this
  # dodgy trying to set this up as have to run install
  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi:/srv/app

  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  medusa:
    ports:
      - ${MEDUSA_STOREFRONT_API_PORT}:80

  minio:
    command: server /data --address ":${MINIO_PORT}" --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}

  medusa-admin:
    ports:
      - ${MEDUSA_ADMIN_PANEL_PORT}:80

  frontend:
#    build:
#      context: frontend
#      dockerfile: development.dockerfile
    volumes:
      # TODO: where is serve??
      # TODO: gotta be a better way to do this... done to avoid crap getting put on local disk
      - ./frontend/pages:/srv/app/pages
      - ./frontend/public:/srv/app/public
      - ./frontend/styles:/srv/app/styles
      - ./frontend/next.config.js:/srv/app/next.config.js
      - ./frontend/next-env.d.ts:/srv/app/next-env.d.ts
      - ./frontend/tsconfig.json:/srv/app/tsconfig.json
      - ./frontend/.eslintrc.json:/srv/app/eslintrc.json
    command: [ 'npm', 'run', 'dev' ]
