version: '3.9'

services:
  mock-api:
    image: mockoon/cli:2.1.0
    volumes:
      - ./openapi.yaml:/srv/app/openapi.yaml
    command: [ 'mockoon-cli', 'start', '--data', '/srv/app/openapi.yaml' ]
    ports:
      - '81:3000'

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile 
    volumes:
      # TODO: where is serve??
      # TODO: gotta be a better way to do this... done to avoid crap getting put on local disk
      - ./frontend/pages:/srv/app/pages
      - ./frontend/components:/srv/app/components
      - ./frontend/public:/srv/app/public
      - ./frontend/styles:/srv/app/styles
      - ./frontend/next.config.js:/srv/app/next.config.js
      - ./frontend/next-env.d.ts:/srv/app/next-env.d.ts
      - ./frontend/tsconfig.json:/srv/app/tsconfig.json
      - ./frontend/.eslintrc.json:/srv/app/eslintrc.json
    ports:
      - "80:3000"
    command: [ 'npm', 'run', 'dev' ]
