openapi: 3.0.3
info:
  title: primal kitchen api atm no admin only routes...
  version: 1.0.0
  
components:
  schemas:
    error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          
    timestamp:
      type: string
    
    item-id:
      type: string
          
    meal:
      type: object
      properties:
        id:
         $ref: "#/components/schemas/item-id"
        name:
          type: string
        price:
          type: integer
          format: int32
          description: "cents"
          minimum: 0 
        day-delivered:
          type: string
          enum:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday
        sizes:
          type: array
          items:
            type: string
            enum:
              - regular
              - warrior
              - family

    meal-pack:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        meals:
          type: array
          items:
            $ref: "#/components/schemas/meal"
            
    order:
      type: object
      properties:
        id:
          type: string
        timestamp:
          $ref: "#/components/schemas/timestamp"

    address:
      description: "doesn't include rural, po box, or private bag"
      type: object
      properties:
        unit-number:
          description: ""
          type: string
        street-number:
          type: string
        street:
          type: string
        suburb:
          type: string

    user:
      type: object
      properties:
        id:
          type: string
        first-name:
          type: string
        last-name:
          type: string
        email-address:
          type: string
        phone-number:
          type: string
        address:
          $ref: "#/components/schemas/address"
  
  parameters:
    item-id:
      name: item-id
      in: path
      required: true
      schema:
        type: string

  responses:
    success-ok:
      description: '200'
    success-created: 
      description: '201'
    success-no-content:
      description: '204'
    
    error-bad-request:
      description: '400'
    error-unauthorized:
      description: '401'
    error-forbidden:
      description: '403'
    error-not-found:
      description: '404'
    error-request-timeout:
      description: '408'  
    error-conflict:
      description: '409'
    error-gone:
      description: '410'
    error-precondition-failed:
      description: '412'
    error-payload-too-large:
      description: '413'
    error-unsupported-media-type:
      description: '415'
    error-too-many-requests:
      description: '429'
    error-request-header-too-large:
      description: '431'
      
    error-internal-server-error:
      description: '500'
    error-not-implemented:
      description: '501'
    error-service-unavailable:
      description: '503'
    
paths:
  /menu/single-meals:
    get:
      responses:
        '200':
          description: recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/meal"
   
  /menu/meal-packs:
    get:
      responses:
        '200':
          description: recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/meal-pack"

  /menu/deli:
    get:
      responses:
        '200':
          description: recipes
          content:
            application/json:
              schema:
                type:
                  object
                  
  /menu/extras:
    get:
      responses:
        '200':
          description: recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/meal'

  /menu/extras/{item-id}:
    get:
      parameters:
        - $ref: '#/components/parameters/item-id'
          
      responses:
        '200':
          description: get extra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/meal'

  /user:
    post:
      responses:
        '200':
          description: logged in
          content:
            application/json:
              schema:
                type: object

  /user/me:
    get:
      responses:
        '200':
          description: get info incase forgor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"

    patch:
      responses:
        '200':
          description: update say address...
          content:
            application/json:
              schema:
                type: object

  /user/me/orders:
    get:
      responses:
        '200':
          description: logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/order"

    post:
      responses:
        '201':
          description: create an order
          content:
            application/json:
              schema:
                type: object

  /user/me/cart:
    get:
      responses:
        '200':
          description: cart
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/meal"

  /user/me/cart/items:
    post:
      responses:
        '200':
          description: add an item to cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  quantity:
                    type: number
                  item:
                    $ref: "#/components/schemas/meal"

  /user/me/cart/items/{item-id}:
    delete:
      parameters:
        - $ref: '#/components/parameters/item-id'
        
      responses:
        '200':
          description: remove item from cart

    patch:
      parameters:
        - $ref: '#/components/parameters/item-id'
        
      responses:
        '200':
          description: update quantity
          content:
            application/json:
              schema:
                type: object
                properties:
                  quantity:
                    type: number
                    minimum: 1
