name: 'deploy'
on:
  workflow_dispatch:

jobs:
  # test:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: adsf
        run: ls

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: login to register
      - name:

