#- name: setup locally signed ssl by mkcert
- import_playbook: playbook-ssl.development.yaml

# - name: install docker etc
- import_playbook: playbook-install-docker.yaml

- name:
  hosts: all
  vars:
    app_directory: /home/primal-kitchen/primal-kitchen

  tasks: 
    - name: ensure destination directory for docker-compose files exists
      file: 
        path: '{{ app_directory }}'
        state: directory

    - name: copy across docker-compose file
      become: yes
      copy:
        src: '{{ playbook_dir }}/../docker-compose.yaml'
        dest: '{{ app_directory }}/docker-compose.yaml'

    - name: copy across development docker-compose file
      become: yes
      copy:
        src: '{{ playbook_dir }}/../docker-compose.development.yaml'
        dest: '{{ app_directory }}/docker-compose.development.yaml'

    - name: copy across env
      become: yes
      copy:
        src: '{{ playbook_dir }}/../.env'
        dest: '{{ app_directory }}/.env'

# - import_playbook: playbook-start.development.yaml
- import_playbook: playbook-start.development.frontend-only.yaml
