- name: no more pets
  hosts: all
  become: yes
  tasks:
    - name: add docker gpg apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: install docker
      apt: 
        name: docker-ce
        state: present

    - name: create docker group
      group:
        name: docker
        state: present

    - name: add user to docker group
      user:
        name: vagrant 
        groups: docker 
        append: yes 

    - name: enable docker
      service: 
        name: docker 
        state: started 
        enabled: yes

    - name: install docker-compose
      get_url: 
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        group: docker 
        mode: g+x

    - name: symlink docker-compose
      file:
        state: link
        src: /usr/local/bin/docker-compose
        path: /usr/bin/docker-compose
        group: docker
        mode: g+x

    - name: setup ssl
      command: docker-compose --file docker-compose.setup.yaml up

    - name: start services
      command: docker-compose --file docker-compose.development.yaml --file docker-compose.yaml up

# install docker 
# install docker compose
# pull in repo
# setup ssl
