name: 'build-and-push-image'
on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        description: 'used to name the image — convention is matching this in docker-compose'
        required: true
        type: string
      SERVICE_DIRECTORY:
        description: 'the directory in the repo this service lives — needed to build the image'
        required: true
        type: string
    secrets:
      CD_DIGITALOCEAN_ACCESS_TOKEN:
        required: true
      APP_CONTAINER_REGISTRY:
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
      # unfortunately can't use github action "env" section to set this env variable...
      - name: set $IMAGE_NAME environment varaible
        run: echo "IMAGE_NAME=${{ secrets.APP_CONTAINER_REGISTRY }}/${{ inputs.SERVICE_NAME }}" >> $GITHUB_ENV

      - name: checkout repository
        uses: actions/checkout@v2

      - name: build image
        run: docker image build --tag ${{ env.IMAGE_NAME }} ${{ inputs.SERVICE_DIRECTORY }}

      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.CD_DIGITALOCEAN_ACCESS_TOKEN }}

      - name: login to digital ocean container registry
        run: doctl registry login # --expiry-seconds 600 # short-lived credentials?

      - name: push image
        run: docker push ${{ env.IMAGE_NAME }}
