name: 'build-and-push-strapi'
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-and-push-strapi.yaml'
      - 'strapi/**'
  workflow_dispatch: # allow manual triggering

jobs:
  build-and-push-strapi:
    uses: primal-kitchen/primal-kitchen/.github/workflows/build-and-push-image.yaml@master
    with:
      SERVICE_NAME: strapi
      SERVICE_DIRECTORY: strapi
    secrets:
      CD_DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.CD_DIGITALOCEAN_ACCESS_TOKEN }}
      APP_CONTAINER_REGISTRY: ${{ secrets.APP_CONTAINER_REGISTRY }}
