name: 'build-and-push-image'
on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        description: 'used to name the image — convention is matching this in docker-compose'
        required: true
        type: string
      DIRECTORY_NAME:
        description: 'the directory in the repo this service lives — needed to build the image'
        required: true
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true

env:
  REGISTRY_HOST: registry.digitalocean.com
  REGISTRY_NAME: primal-kitchen

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    # env:
    #  IMAGE_NAME: ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}
    steps:
      - name: set $IMAGE_NAME environment varaible
        run: echo "IMAGE_NAME=$REGISTRY_HOST/$REGISTRY_NAME/$SERVICE_NAME" >> $GITHUB_ENV

      - uses: actions/checkout@v2 # needed when doing stuff on code from repo it seems...

      - name: build image
        run: docker image build --tag $IMAGE_NAME

      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.PRIMAL_KITCHEN_DIGITALOCEAN_ACCESS_TOKEN }}

      - name: login to digital ocean container registry
        run: doctl registry login # --expiry-seconds 600 # short-lived credentials?

      - name: push image
        run: docker push $IMAGE_NAME
