name: 'build-and-push-frontend'
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-and-push-frontend.yaml'
      - 'frontend/**'
  workflow_dispatch: # allow manual triggering

jobs:
  build-and-push-frontend:
    uses: primal-kitchen/primal-kitchen/.github/workflows/build-and-push-image.yaml@master
    with:
      SERVICE_NAME: frontend
      SERVICE_DIRECTORY: frontend
    secrets:
      CD_DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.CD_DIGITALOCEAN_ACCESS_TOKEN }}


