name: 'build-and-push-reverse-proxy'
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-and-push-reverse-proxy.yaml'
      - 'reverse-proxy/**'
  workflow_dispatch: # allow manual triggering

jobs:
  build-and-push-reverse-proxy:
    uses: primal-kitchen/primal-kitchen/.github/workflows/build-and-push-image.yaml@master
    with:
      SERVICE_NAME: reverse-proxy
      SERVICE_DIRECTORY: reverse-proxy
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.CD_DIGITALOCEAN_ACCESS_TOKEN }}
