name: 'create-env-file-on-server'
on: workflow_dispatch
jobs:
  create-env-file-on-server:
    runs-on: ubuntu-20.04
    steps:
      - name: 'calculate-timestamp'
        id: timestamp
        run: echo "::set-output name=timestamp::$(date --utc +'%FT%TZ')"

      - name: 'create-env-file'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_DOMAIN }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CD_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.CD_SSH_PRIVATE_KEY_PASSPHRASE }} # added security
          # TODO: fingerprint validation
          script_stop: true # stop after first failure in script
          script: |
            cd ${{ secrets.SERVER_APP_DIRECTORY }}
            rm --force .env # force is needed to prevent error if not exists

            add_variable() { echo $1 >> .env ; }
            add_comment() { echo "\n# $1" >> .env ; }

            echo "created by github action [${{ steps.timestamp.outputs.timestamp }}]" >> .env
            add_variable "APP_DOMAIN=${{ secrets.APP_DOMAIN }}"
            add_variable "APP_CONTAINER_REGISTRY=${{ secrets.APP_CONTAINER_REGISTRY }}"
            add_variable "APP_DEVELOPER_EMAIL=${{ secrets.APP_DEVELOPER_EMAIL }}"
            add_variable "SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}"
            add_variable "SERVER_APP_DIRECTORY=${{ secrets.SERVER_APP_DIRECTORY }}"
            add_variable "SSL_CERTIFICATE_FILE=${{ secrets.SSL_CERTIFICATE_FILE }}"
            add_variable "SSL_CERTIFICATE_PRIVATE_KEY_FILE=${{ secrets.SSL_CERTIFICATE_PRIVATE_KEY_FILE }}"

            add_comment "postgres"
            add_variable "POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}"
            add_variable "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
            add_variable "POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}"
            add_variable "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}"
            add_variable "POSTGRES_VOLUME=${{ secrets.POSTGRES_VOLUME }}"
            add_variable "POSTGRES_USING_SSL=${{ secrets.POSTGRES_USING_SSL }}"
            add_variable "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}"
            
            add_comment "strapi"
            add_variable "STRAPI_USERNAME=${{ secrets.STRAPI_USERNAME }}"
            add_variable "STRAPI_PASSWORD=${{ secrets.STRAPI_PASSWORD }}"
            add_variable "STRAPI_HOST_URL=${{ secrets.STRAPI_HOST_URL }}"
            add_variable "STRAPI_PORT=${{ secrets.STRAPI_PORT }}"
            add_variable "STRAPI_ADMIN_JWT_SECRET=${{ secrets.STRAPI_ADMIN_JWT_SECRET }}"
            add_variable "STRAPI_CONTAINER_NAME=${{ secrets.STRAPI_CONTAINER_NAME }}"
            add_variable "STRAPI_SUBDOMAIN=${{ secrets.STRAPI_SUBDOMAIN }}"

            add_comment "redis"
            add_variable "REDIS_PORT=${{ secrets.REDIS_PORT }}"

            add_comment "minio"
            add_variable "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}"
            add_variable "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}"
            add_variable "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}"
            add_variable "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}"
            add_variable "MINIO_HOSTNAME=${{ secrets.MINIO_HOSTNAME }}"
            add_variable "MINIO_PORT=${{ secrets.MINIO_PORT }}"
            add_variable "MINIO_CONSOLE_PORT=${{ secrets.MINIO_CONSOLE_PORT }}"
            add_variable "MINIO_BUCKET=${{ secrets.MINIO_BUCKET }}"
            add_variable "MINIO_SUBDOMAIN=${{ secrets.MINIO_SUBDOMAIN }}"
            add_variable "MINIO_CONTAINER_NAME=${{ secrets.MINIO_CONTAINER_NAME }}"

            add_comment "medusa"
            add_variable "MEDUSA_STOREFRONT_API_PORT=${{ secrets.MEDUSA_STOREFRONT_API_PORT }}"
            add_variable "MEDUSA_STOREFRONT_SUBDOMAIN=${{ secrets.MEDUSA_STOREFRONT_SUBDOMAIN }}"
            add_variable "MEDUSA_STOREFRONT_CONTAINER_NAME=${{ secrets.MEDUSA_STOREFRONT_CONTAINER_NAME }}"
            add_variable "MEDUSA_STOREFRONT_COOKIE_SECRET=${{ secrets.MEDUSA_STOREFRONT_COOKIE_SECRET }}"
            add_variable "MEDUSA_STOREFRONT_JWT_SECRET=${{ secrets.MEDUSA_STOREFRONT_JWT_SECRET }}"

            add_comment "medusa admin"
            add_variable "MEDUSA_ADMIN_PANEL_PORT=${{ secrets.MEDUSA_ADMIN_PANEL_PORT }}"
            add_variable "MEDUSA_ADMIN_PANEL_CONTAINER_NAME=${{ secrets.MEDUSA_ADMIN_PANEL_CONTAINER_NAME }}"
            add_variable "MEDUSA_ADMIN_PANEL_SUBDOMAIN=${{ secrets.MEDUSA_ADMIN_PANEL_SUBDOMAIN }}"
            add_variable "MEDUSA_ADMIN_EMAIL=${{ secrets.MEDUSA_ADMIN_EMAIL }}"
            add_variable "MEDUSA_ADMIN_PASSWORD=${{ secrets.MEDUSA_ADMIN_PASSWORD }}"

            add_comment "frontend"
            add_variable "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}"
            add_variable "FRONTEND_CONTAINER_NAME=${{ secrets.FRONTEND_CONTAINER_NAME }}"

            add_comment "nginx"
            add_variable "NGINX_WEBROOT=${{ secrets.NGINX_WEBROOT }}"
