name: 'deploy'
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'choose the image to deploy'
        type: choice
        options:
          - frontend
          - reverse-proxy
          - medusa
          - medusa-admin
          - strapi
        required: true

# TODO: get image and service name from inputs
env:
  REGISTRY_HOST: registry.digitalocean.com
  REGISTRY_NAME: primal-kitchen
  IMAGE: frontend
  SERVICE: frontend

jobs:
  deploy_image:
    runs-on: ubuntu-20.04
    steps:
      - name: 'pull and deploy image'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PRIVATE_KEY_PASSPHRASE }} # added security
          # TODO: fingerprint validation
          script_stop: true # stop after first failure in script
          script: |
            # login to container registry
            mkdir -p ~/.config # doctl command below won't work if directory doesn't exist
            doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            # doctl registry login
            # pull corresponding image
            docker pull ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE }}
            # restart container in place
            ls
            cd ~/primal-kitchen/primal-kitchen/
            ls
            docker-compose up --detach --no-deps ${{ env.SERVICE }}
            # TODO: remove old container
            # TODO: remove old image


