name: 'deploy'
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'choose the image to deploy'
        type: choice
        options:
          - frontend
          - reverse-proxy
          - medusa
          - medusa-admin
          - strapi
        required: true

jobs:
  deploy_image:
    runs-on: ubuntu-20.04
    steps:
      - name: ''
        uses: appleboy/ssh-action@master
        # TODO: get image and service name from inputs
        env:
          REGISTRY_HOST: registry.digitalocean.com
          REGISTRY_NAME: primal-kitchen
          IMAGE: frontend
          SERVICE: frontend
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PRIVATE_KEY_PASSPHRASE }} # added security
          # TODO: fingerprint validation
          script_stop: true # stop after first failure in script
          script: |
            # login to container registry
            # echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin $REGISTRY_HOST
            mkdir -p ~/.config # doctl command below won't work if directory doesn't exist
            doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            # doctl registry login --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            # pull corresponding image
            doctl registry login
            docker pull $REGISTRY_HOST/$REGISTRY_NAME/$IMAGE
            # restart container in place
            docker compose up --detach --no-deps $SERVICE
            # TODO: remove old container
            # TODO: remove old image


